# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "azure-$(Build.BuildId)"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: BuildTestImage
        displayName: Build test image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build test image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)-test"
              arguments: "--target test"
          - task: Docker@2
            displayName: Push test image
            inputs:
              containerRegistry: 'slow-sinatra-docker-connection'
              repository: 'teefour/slow-sinatra'
              command: 'push'
              tags: '$(tag)-test'
      - job: RunTest
        displayName: Run tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Log in to Docker registry
            inputs:
              containerRegistry: 'slow-sinatra-docker-connection'
              command: 'login'
          - script: "docker run teefour/slow-sinatra:$(tag)-test"
            displayName: Run test container
  - stage: Build
    dependsOn: Test
    displayName: Build
    jobs:
      - job: BuildAppImage
        displayName: Build app image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build app image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)"
              arguments: "--target production"
          - task: Docker@2
            displayName: Push app image
            inputs:
              containerRegistry: 'slow-sinatra-docker-connection'
              repository: 'teefour/slow-sinatra'
              command: 'push'
              tags: '$(tag)'
