# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "azure-$(Build.BuildId)"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: build_test
        displayName: Build test image
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'slow-sinatra-docker-connection'
            repository: 'teefour/slow-sinatra'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)-test'
            arguments: '--target test'
        - task: Docker@2
          inputs:
            containerRegistry: 'slow-sinatra-docker-connection'
            repository: 'teefour/slow-sinatra'
            command: 'push'
            tags: '$(tag)-test'


# stages:
#   - stage: Build
#     displayName: Build image
#     dependsOn: Test
#     jobs:
#       - job: Build
#         displayName: Build
#         pool:
#           vmImage: ubuntu-latest
#         steps:
#           - task: Docker@2
#             displayName: Build an image
#             inputs:
#               containerRegistry: "slow-sinatra-docker-connection"
#               repository: "teefour/slow-sinatra"
#               command: "buildAndPush"
#               Dockerfile: "**/Dockerfile"
#               tags: "$(tag)"
