# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "azure-$(Build.BuildId)"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: BuildAndRunTest
        displayName: Build and run test image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build test image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)-test"
              arguments: "--target test"
          - script: "docker run teefour/slow_sinatra:$(tag)-test"
            displayName: Run test container
# stages:
#   - stage: Build
#     displayName: Build image
#     dependsOn: Test
#     jobs:
#       - job: Build
#         displayName: Build
#         pool:
#           vmImage: ubuntu-latest
#         steps:
#           - task: Docker@2
#             displayName: Build an image
#             inputs:
#               containerRegistry: "slow-sinatra-docker-connection"
#               repository: "teefour/slow-sinatra"
#               command: "buildAndPush"
#               Dockerfile: "**/Dockerfile"
#               tags: "$(tag)"
