trigger:
  - main

# Disable pull request trigger
pr: none

resources:
  - repo: self

variables:
  tag: "azure-0.0.6-$(Build.BuildId)"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: BuildTestImage
        displayName: Build test image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build test image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)-test"
              arguments: "--target test"
          - task: Docker@2
            displayName: Push test image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "push"
              tags: "$(tag)-test"
      - job: RunTest
        displayName: Run tests
        dependsOn: BuildTestImage
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Log in to Docker registry
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              command: "login"
          - script: "docker run teefour/slow-sinatra:$(tag)-test"
            displayName: Run test container
  - stage: Build
    dependsOn: Test
    displayName: Build
    jobs:
      - job: BuildAppImage
        displayName: Build app image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build app image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)"
              arguments: "--target production"
          - task: Docker@2
            displayName: Push app image
            inputs:
              containerRegistry: "slow-sinatra-docker-connection"
              repository: "teefour/slow-sinatra"
              command: "push"
              tags: "$(tag)"
  - stage: Deploy
    dependsOn: Build
    displayName: Deploy
    jobs:
      - job: DeployProductionContainer
        displayName: Deploy production container
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: "Azure subscription 1(e0f0ade8-e98d-4cd3-b3e2-41fa60632b0d)"
              appName: "slow-sinatra"
              containers: "index.docker.io/teefour/slow-sinatra:$(tag)"
